"use client";
import { useEffect, useState } from "react";
import { ImagePlus, MessageCircle, Mic, Plus, Send, Square, Volume2, X } from "lucide-react";
import { addDoc, collection, getDocs, limit, orderBy, query, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useDashboard } from "@/context/DashboardContext";
type Message = { role: "assistant" | "user"; text: string; image?: string | null };
export default function FarmChat() { const { farm, user } = useDashboard(); const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[image,setImage]=useState<string|null>(null),[sending,setSending]=useState(false),[recorder,setRecorder]=useState<MediaRecorder|null>(null),[sessionId,setSessionId]=useState<string|null>(null),[newChat,setNewChat]=useState(false);
useEffect(()=>{ if(!open||!user||sessionId||newChat)return; getDocs(query(collection(db,"farmers",user.uid,"chatSessions"),orderBy("updatedAt","desc"),limit(1))).then(async s=>{const x=s.docs[0];if(!x)return;setSessionId(x.id);const m=await getDocs(query(collection(db,"farmers",user.uid,"chatSessions",x.id,"messages"),orderBy("createdAt","asc"),limit(80)));setMessages(m.docs.map(d=>({role:d.data().role==="assistant"?"assistant":"user",text:String(d.data().text??""),image:d.data().image??null})));}).catch(()=>undefined);},[open,user,sessionId,newChat]);
const speak=async(text:string)=>{const r=await fetch("/api/chat/speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});if(r.ok)new Audio(URL.createObjectURL(await r.blob())).play().catch(()=>undefined);};
const send=async()=>{if((!draft.trim()&&!image)||sending||!user)return;const text=draft.trim()||"Please inspect this farm image.";const attachment=image;setDraft("");setImage(null);setSending(true);setMessages(m=>[...m,{role:"user",text,image:attachment}]);try{let id=sessionId;if(!id){const c=await addDoc(collection(db,"farmers",user.uid,"chatSessions"),{title:text.slice(0,56),language:farm?.language||"en",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});id=c.id;setSessionId(id);setNewChat(false);}await addDoc(collection(db,"farmers",user.uid,"chatSessions",id,"messages"),{role:"user",text,image:attachment,createdAt:serverTimestamp()});await addDoc(collection(db,"farmers",user.uid,"farmNotes"),{note:text,source:"chat",createdAt:serverTimestamp()});const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,imageDataUrl:attachment,language:farm?.language||"English",history:messages,farm:{lga:farm?.lga,state:farm?.state,crops:farm?.crops,soilSummary:farm?.soilSummary}})});const d=await r.json();const reply=r.ok?d.reply:"The farm assistant is temporarily unavailable. Please try again.";setMessages(m=>[...m,{role:"assistant",text:reply}]);await addDoc(collection(db,"farmers",user.uid,"chatSessions",id,"messages"),{role:"assistant",text:reply,createdAt:serverTimestamp()});}finally{setSending(false);}};
const voice=async()=>{if(recorder){recorder.stop();setRecorder(null);return;}try{const s=await navigator.mediaDevices.getUserMedia({audio:true}),r=new MediaRecorder(s),parts:Blob[]=[];r.ondataavailable=e=>parts.push(e.data);r.onstop=async()=>{s.getTracks().forEach(t=>t.stop());const f=new FormData();f.append("audio",new File([new Blob(parts)],"voice.webm"));const x=await fetch("/api/chat/transcribe",{method:"POST",body:f}),d=await x.json();if(x.ok)setDraft(v=>`${v}${v?" ":""}${d.text}`);};r.start();setRecorder(r);}catch{}};
return <div className="fixed bottom-5 right-5 z-[70]">{open?<section className="mb-3 flex h-[min(38rem,calc(100vh-7rem))] w-[min(25rem,calc(100vw-2rem))] flex-col overflow-hidden rounded-3xl border border-[#cfe4d4] bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#087a3d] px-4 py-4 text-white"><div><p className="font-bold">Pangolin-X Farm Assistant</p><p className="text-xs text-white/75">Your connected farm intelligence</p></div><div><button onClick={()=>{setNewChat(true);setSessionId(null);setMessages([]);}} className="p-2"><Plus/></button><button onClick={()=>setOpen(false)} className="p-2"><X/></button></div></header><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.map((m,i)=><div key={i} className={`max-w-[88%] break-words whitespace-pre-wrap rounded-2xl px-3 py-2.5 text-sm leading-6 ${m.role==="user"?"ml-auto bg-[#087a3d] text-white":"bg-[#eef4ec] text-[#183127]"}`}>{m.image?<img src={m.image} alt="Farm upload" className="mb-2 max-h-40 rounded-xl object-cover"/>:null}{m.text}{m.role==="assistant"?<button onClick={()=>void speak(m.text)} className="ml-2"><Volume2 className="inline h-4 w-4"/></button>:null}</div>)}{!messages.length?<p className="rounded-2xl bg-[#eef4ec] p-4 text-sm">Hello. Ask about your crops, field conditions, or send a farm photo.</p>:null}{sending?<p className="text-sm text-[#617067]">Thinking…</p>:null}</div><div className="border-t p-3">{image?<div className="mb-2 inline-flex items-center gap-2 rounded-xl border border-[#d5e2d3] p-1"><img src={image} alt="Selected farm upload" className="h-12 w-12 rounded-lg object-cover"/><button onClick={()=>setImage(null)} className="text-xs text-[#a2423b]">Remove</button></div>:null}<div className="flex items-end gap-2"><label className="p-2 text-[#166534]"><ImagePlus/><input className="hidden" type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f||f.size>4*1024*1024)return;const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(f);}}/></label><button onClick={()=>void voice()} className="p-2 text-[#166534]">{recorder?<Square className="text-red-600"/>:<Mic/>}</button><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} rows={1} className="max-h-28 min-w-0 flex-1 resize-none rounded-xl border px-3 py-2" placeholder="Ask about your farm"/><button onClick={()=>void send()} className="rounded-xl bg-[#087a3d] p-2.5 text-white"><Send/></button></div></div></section>:null}<button onClick={()=>setOpen(v=>!v)} className="ml-auto grid h-14 w-14 place-items-center rounded-full bg-[#0b9a49] text-white shadow-lg"><MessageCircle/></button></div>; }
