"use client";
import { useState } from "react";
import { ImagePlus, MessageCircle, Mic, Send, Square, Volume2, X } from "lucide-react";
import { useDashboard } from "@/context/DashboardContext";

type Message = { role: "assistant" | "user"; text: string };
export default function FarmChat() {
  const { farm } = useDashboard(); const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [draft, setDraft] = useState(""); const [image, setImage] = useState<string | null>(null); const [sending, setSending] = useState(false); const [recorder, setRecorder] = useState<MediaRecorder | null>(null);
  const send = async () => { if ((!draft.trim() && !image) || sending) return; const text = draft.trim() || "Please inspect this farm image."; setDraft(""); setSending(true); setMessages((m) => [...m, { role: "user", text }]); try { const res = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text, imageDataUrl: image, language: farm?.language || "English", history: messages, farm: { lga: farm?.lga, state: farm?.state, crops: farm?.crops, soilSummary: farm?.soilSummary } }) }); const data = await res.json(); setImage(null); setMessages((m) => [...m, { role: "assistant", text: res.ok ? data.reply : "The farm assistant is temporarily unavailable. Please try again." }]); } finally { setSending(false); } };
  const voice = async () => { if (recorder) { recorder.stop(); setRecorder(null); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const r = new MediaRecorder(stream); const parts: Blob[] = []; r.ondataavailable = (e) => parts.push(e.data); r.onstop = async () => { stream.getTracks().forEach((t) => t.stop()); const form = new FormData(); form.append("audio", new File([new Blob(parts)], "voice.webm")); const res = await fetch("/api/chat/transcribe", { method: "POST", body: form }); const data = await res.json(); if (res.ok) setDraft((d) => `${d}${d ? " " : ""}${data.text}`); }; r.start(); setRecorder(r); } catch { /* permission is handled by the browser */ } };
  const speak = async (text: string) => { const res = await fetch("/api/chat/speech", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text }) }); if (res.ok) new Audio(URL.createObjectURL(await res.blob())).play().catch(() => undefined); };
  return <div className="fixed bottom-5 right-5 z-[70]">{open ? <section className="mb-3 flex h-[min(38rem,calc(100vh-7rem))] w-[min(25rem,calc(100vw-2rem))] flex-col overflow-hidden rounded-3xl border border-[#cfe4d4] bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#087a3d] px-4 py-4 text-white"><div><p className="font-bold">Pangolin-X Farm Assistant</p><p className="text-xs text-white/75">Your connected farm intelligence</p></div><button onClick={() => setOpen(false)} className="p-2"><X /></button></header><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.length ? messages.map((m, i) => <div key={i} className={`max-w-[88%] break-words whitespace-pre-wrap rounded-2xl px-3 py-2.5 text-sm leading-6 ${m.role === "user" ? "ml-auto bg-[#087a3d] text-white" : "bg-[#eef4ec] text-[#183127]"}`}>{m.text}{m.role === "assistant" ? <button onClick={() => void speak(m.text)} className="ml-2 inline-flex align-middle text-[#087a3d]" aria-label="Listen"><Volume2 className="h-4 w-4" /></button> : null}</div>) : <p className="rounded-2xl bg-[#eef4ec] p-4 text-sm leading-6 text-[#183127]">Hello. Ask about your crops, field conditions, or send a farm photo.</p>}{sending ? <p className="text-sm text-[#617067]">Thinking…</p> : null}</div><div className="border-t border-[#e2e9df] p-3">{image ? <p className="mb-2 text-xs text-[#166534]">Photo attached <button onClick={() => setImage(null)} className="underline">remove</button></p> : null}<div className="flex items-end gap-2"><label className="rounded-xl p-2 text-[#166534] hover:bg-[#eef4ec]"><ImagePlus className="h-5 w-5" /><input className="hidden" type="file" accept="image/*" onChange={(e) => { const f = e.target.files?.[0]; if (!f || f.size > 4 * 1024 * 1024) return; const r = new FileReader(); r.onload = () => setImage(String(r.result)); r.readAsDataURL(f); }} /></label><button onClick={() => void voice()} className="rounded-xl p-2 text-[#166534] hover:bg-[#eef4ec]" aria-label="Voice input">{recorder ? <Square className="h-5 w-5 text-red-600" /> : <Mic className="h-5 w-5" />}</button><textarea value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); void send(); } }} rows={1} className="max-h-28 min-w-0 flex-1 resize-none rounded-xl border border-[#d5e2d3] px-3 py-2 text-sm leading-5 outline-none focus:border-[#087a3d]" placeholder="Ask about your farm" /><button onClick={() => void send()} className="rounded-xl bg-[#087a3d] p-2.5 text-white"><Send className="h-4 w-4" /></button></div></div></section> : null}<button onClick={() => setOpen((v) => !v)} className="ml-auto grid h-14 w-14 place-items-center rounded-full bg-[#0b9a49] text-white shadow-lg"><MessageCircle className="h-6 w-6" /></button></div>;
}
